#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

cert_dir="certs"
cert_name="${SHINE_DESKTOP_CERT_NAME:-RMKCET Shine Local Code Signing}"
publisher="${SHINE_DESKTOP_PUBLISHER_DISPLAY_NAME:-RMKCET Shine}"
pfx_path="$cert_dir/shine-selfsigned-codesign.pfx"
crt_path="$cert_dir/shine-selfsigned-codesign.crt"
key_path="$cert_dir/shine-selfsigned-codesign.key"
cnf_path="$cert_dir/shine-selfsigned-codesign.cnf"
env_path=".release-local.env"
cmd_env_path=".release-local.cmd"

if ! command -v openssl >/dev/null 2>&1; then
  echo "[ERROR] openssl is required to create the self-signed code-signing certificate." >&2
  exit 1
fi

mkdir -p "$cert_dir"
chmod 700 "$cert_dir"

password="${SHINE_DESKTOP_CERT_PASSWORD:-}"
if [ -z "$password" ]; then
  password="$(openssl rand -base64 24 | tr -d '\n')"
fi

cat > "$cnf_path" <<EOF
[req]
default_bits = 3072
prompt = no
default_md = sha256
distinguished_name = dn
x509_extensions = v3_codesign

[dn]
CN = $cert_name
O = $publisher

[v3_codesign]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature
extendedKeyUsage = codeSigning
subjectKeyIdentifier = hash
EOF

openssl req \
  -x509 \
  -newkey rsa:3072 \
  -nodes \
  -days 825 \
  -keyout "$key_path" \
  -out "$crt_path" \
  -config "$cnf_path" >/dev/null 2>&1

openssl pkcs12 \
  -export \
  -out "$pfx_path" \
  -inkey "$key_path" \
  -in "$crt_path" \
  -name "$cert_name" \
  -passout "pass:$password" >/dev/null 2>&1

chmod 600 "$key_path" "$pfx_path" "$env_path" 2>/dev/null || true

cat > "$env_path" <<EOF
# Local desktop release signing env.
# Generated by desktop/scripts/create-self-signed-cert.sh.
# Do not commit this file.
export SHINE_DESKTOP_CERT_PATH="$(pwd)/$pfx_path"
export SHINE_DESKTOP_CERT_PASSWORD="$password"
export SHINE_DESKTOP_PUBLISHER_DISPLAY_NAME="$publisher"
export SHINE_DESKTOP_PACKAGE_PUBLISHER="CN=$cert_name"
EOF

cat > "$cmd_env_path" <<EOF
@echo off
rem Local desktop release signing env.
rem Generated by desktop/scripts/create-self-signed-cert.sh.
rem Do not commit this file.
set "SHINE_DESKTOP_CERT_PATH=$(pwd -W 2>/dev/null || pwd)/$pfx_path"
set "SHINE_DESKTOP_CERT_PASSWORD=$password"
set "SHINE_DESKTOP_PUBLISHER_DISPLAY_NAME=$publisher"
set "SHINE_DESKTOP_PACKAGE_PUBLISHER=CN=$cert_name"
EOF

chmod 600 "$env_path"
chmod 600 "$cmd_env_path"

echo "[desktop-release] Self-signed code-signing certificate created:"
echo "  PFX : $(pwd)/$pfx_path"
echo "  CRT : $(pwd)/$crt_path"
echo "  ENV : $(pwd)/$env_path"
echo "  CMD : $(pwd)/$cmd_env_path"
echo
echo "Before building a release, run:"
echo "  source desktop/.release-local.env"
echo
echo "To reduce warnings on a Windows test machine, import the CRT into Trusted Root Certification Authorities and Trusted Publishers."
