$ErrorActionPreference = "Stop"

$DesktopRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$CertDir = Join-Path $DesktopRoot "certs"
$CertName = if ($env:SHINE_DESKTOP_CERT_NAME) { $env:SHINE_DESKTOP_CERT_NAME } else { "RMKCET Shine Local Code Signing" }
$Publisher = if ($env:SHINE_DESKTOP_PUBLISHER_DISPLAY_NAME) { $env:SHINE_DESKTOP_PUBLISHER_DISPLAY_NAME } else { "RMKCET Shine" }
$PfxPath = Join-Path $CertDir "shine-selfsigned-codesign.pfx"
$CrtPath = Join-Path $CertDir "shine-selfsigned-codesign.crt"
$EnvPath = Join-Path $DesktopRoot ".release-local.env"
$CmdEnvPath = Join-Path $DesktopRoot ".release-local.cmd"

New-Item -ItemType Directory -Force -Path $CertDir | Out-Null

if ($env:SHINE_DESKTOP_CERT_PASSWORD) {
  $PasswordPlain = $env:SHINE_DESKTOP_CERT_PASSWORD
} else {
  $Bytes = New-Object byte[] 24
  [Security.Cryptography.RandomNumberGenerator]::Fill($Bytes)
  $PasswordPlain = [Convert]::ToBase64String($Bytes)
}

$Password = ConvertTo-SecureString -String $PasswordPlain -Force -AsPlainText
$Cert = New-SelfSignedCertificate `
  -Type CodeSigningCert `
  -Subject "CN=$CertName, O=$Publisher" `
  -CertStoreLocation "Cert:\CurrentUser\My" `
  -KeyAlgorithm RSA `
  -KeyLength 3072 `
  -HashAlgorithm SHA256 `
  -NotAfter (Get-Date).AddYears(2)

Export-PfxCertificate -Cert $Cert -FilePath $PfxPath -Password $Password | Out-Null
Export-Certificate -Cert $Cert -FilePath $CrtPath | Out-Null

@"
# Local desktop release signing env.
# Generated by desktop/scripts/create-self-signed-cert.ps1.
# Do not commit this file.
export SHINE_DESKTOP_CERT_PATH="$($PfxPath -replace "\\", "/")"
export SHINE_DESKTOP_CERT_PASSWORD="$PasswordPlain"
export SHINE_DESKTOP_PUBLISHER_DISPLAY_NAME="$Publisher"
export SHINE_DESKTOP_PACKAGE_PUBLISHER="CN=$CertName"
"@ | Set-Content -Path $EnvPath -Encoding UTF8

@"
@echo off
rem Local desktop release signing env.
rem Generated by desktop/scripts/create-self-signed-cert.ps1.
rem Do not commit this file.
set "SHINE_DESKTOP_CERT_PATH=$PfxPath"
set "SHINE_DESKTOP_CERT_PASSWORD=$PasswordPlain"
set "SHINE_DESKTOP_PUBLISHER_DISPLAY_NAME=$Publisher"
set "SHINE_DESKTOP_PACKAGE_PUBLISHER=CN=$CertName"
"@ | Set-Content -Path $CmdEnvPath -Encoding ASCII

Write-Host "[desktop-release] Self-signed code-signing certificate created:"
Write-Host "  PFX : $PfxPath"
Write-Host "  CRT : $CrtPath"
Write-Host "  ENV : $EnvPath"
Write-Host "  CMD : $CmdEnvPath"
Write-Host ""
Write-Host "The certificate is also in CurrentUser\My. For test PCs, import the CRT into Trusted Root Certification Authorities and Trusted Publishers."
